version: '3.8'

services:
  postgres:
    tty: true
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=starter
      - POSTGRES_USER=starter
      - POSTGRES_DB=starter
    volumes:
      - starter_postgres_data:/var/lib/postgresql/data
  redis:
    tty: true
    container_name: redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - starter_redis_data:/data

volumes:
  starter_postgres_data:
  starter_redis_data: